### PR TITLE
Don't wait twice for mongo

### PR DESCRIPTION
**Pull request by marktheunissen**
@elliotttf Was this put in accidentally? I noticed that we wait for mongo to accept connections in the sample data playbook as well as the controller playbook - by the time we reach this one, it will definitely be running and listening, so can safely remove, as currently it always waits 4 seconds.

### CODE REVIEW

**Comment by elliotttf** [comment]
I had issues before I added the second wait since mongo gets restarted at the end of the last job... the case was this:

**Controller**
1. Start mongo the first time
2. Wait...
3. Crate users
4. ... rest of playbook ...
5. Restart mongo

**Sample data**
1. Create sample data -> fail, mongo's not up yet...

This was _only_ a problem on ec2 (yay could computing). I'm happy to have one removed if it works reliably now though!

**Comment by marktheunissen** [comment]
Ah, great point. How about b37038c? That should give it time to listen to connections.

**Comment by elliotttf** [comment]
Might be worth a shot... when I was testing this originally the ec2 stuff was really finicky and would sometimes work and others not. I'd rather not introduce false positives into the ec2 builds to save 4s :)

**Comment by marktheunissen** [comment]
Yeah, you're right. Ok I'll document it a bit better rather than move it.

**Comment by elliotttf** [comment]
:thumbsup:

**Pull request merged**
