### PR TITLE
TW-78 mongo auth

### PR DESCRIPTION
**Pull request by elliotttf**
This branch creates a mongodb_user ansible script that is now leveraged in the playbooks to create mongo users.

The controller code has also been updated to accept a config file which currently only contains mongo connection info.

### CODE REVIEW

**Comment by elliotttf** [comment]
Note: you'll need to composer.phar update to test that the config file stuff works.

**Comment by marktheunissen** [comment]
One of the problems that was difficult to wrap my head around is where to dump the credentials file .mongodb.cnf. The problem with putting it only in `/root` and then expecting it at `~/.mongodb.cnf` in the python code is that Ansible can be connected to a server as root, or it can sudo to root. When it sudos to root, the $HOME environment var doesn't change, and thus it can be difficult to pick up the credentials if you've dropped them into `/root` only. There was a fix for this in Ansible but it was reverted, as it caused some issues.

The workaround I've used in the updates in the plugin branch is to do figure out where the user's home directory is, register it to a variable, and drop the credentials there, too:

``` yml
- name: MySQL | Get the current users home
  action: shell echo $HOME
  register: user_home

- name: MySQL | Config for easy access as the admin user.
  action: template src=templates/root-my-cnf.j2 dest=${user_home.stdout}/.my.cnf
```

This works as long as we don't reconnect as another user at a later stage and expect to connect to the database, as the .my.cnf creds won't be in the correct place. This is a very edge case, but it's still possible.

One possible solution to this would be to provide a path to a credentials file as an option to the mongodb_user module. I think though that we should be ok for now with dropping the creds in both places.

**Comment by marktheunissen** [comment]
See, I kinda like having the .my.cnf for both the admin user and root user, as it allows me to do `mysql` from anywhere and not supply credentials.

**Comment by marktheunissen** [comment]
This is the feature: https://groups.google.com/forum/?fromgroups=#!msg/ansible-project/cNgOQm-zF0U/RGAg7lp1FPwJ

that was reverted:

https://groups.google.com/forum/?fromgroups=#!searchin/ansible-project/sudo/ansible-project/t-OgbdshT0I/VFxIsMz51xUJ

**Comment by marktheunissen** [comment]
Ansible has a pip module, just making our playbook use that. We should be able to install it just-in-time, and this way the ec2 build will work.

**Comment by marktheunissen** [comment]
Try this on your terminal: `sudo service mongodb restart; mongo`

it barfs
that's the issue i think - it returns saying the process has started, but it hasn't 

will add pause module

**Comment by marktheunissen** [comment]
BOOM. Man that took a lot of debugging - the mongo process starts up and preallocates and optimized some space or something, and doesn't listen until it's done. So, adding the wait_for step in 4a5586e ( :heart: Ansible) makes everything work! In retrospect it shouldn't have taken me so long to debug, but the huge wait between destroying the re-upping the VM is distracting

**Comment by marktheunissen** [comment]
Tested, working, I have to merge this before I leave for vacation, it's a mental thing.

**Pull request merged**
