### PR TITLE
Course creation form

### PR DESCRIPTION
**Pull request by marktheunissen**

### CODE REVIEW

**Comment by elliotttf** [comment]
@marktheunissen I added buttons to remove resources that have been added. Should we protect against removing resources that are expected based on the plugins that were selected?

**Comment by marktheunissen** [comment]
Awesome man, yeah I think that's a good idea.

**Comment by marktheunissen** [comment]
@elliotttf You think this is ready to be merged? I think we should pull the trigger.

**Comment by elliotttf** [comment]
I think there might be an issue with prompting to create the instructor's resources but otherwise is ok.

**Pull request closed without merging**
