### PR TITLE
TW-93 stable build

### PR DESCRIPTION
**Pull request by elliotttf**
This includes changes to the ec2 scripts for separate stable and build machines.

**Assumption**: tw-stable.com will be the host name for the stable server (+1'd by @mirzu)
#### Post-merge work:
- [x] Update the stable build script to track the stable branch

After this is complete, pushes to the stable branch will automatically trigger a rebuild of the stable server. This is easy to disable though if we want the build process to be fully manual.

### CODE REVIEW

**Comment by elliotttf** [comment]
TODO
- Update /etc/hosts and /etc/hostname appropriately
- Don't _need_ bender for the stable machine
- Dynamically pass the branch to checkout

**Comment by elliotttf** [comment]
Note: I went ahead and updated the jenkins job so I don't forget about it.

**Comment by marktheunissen** [comment]
I made a commit that makes the passwords anonymous and instead we send them as environment variables through the Jenkins job config. 

I haven't tested it and I'm not sure it's the perfect approach, and it makes the bash a little inconsistent in how we pass variables to it (sometimes as environment vars, sometimes as params). Perhaps we should make all variables be environment variables passed through the Jenkins jobs?

**Comment by elliotttf** [comment]
Nice! I'll give this a test in a little bit. I'm glad you gave that a look though, it was certainly bothering me to have those in cleartext.

We should probably change the passwords or purge those files from the git history too if we don't want to risk anyone getting access.

**Comment by marktheunissen** [comment]
Hey Elliott, this should be ready for merge.
- I cleaned up a lot - created a /provision directory to hold all the playbooks and stuff. 
- Made files that contain the passwords and other parameters for the build - I've placed those on the build control server rather than have them as env variables in Jenkins.
- Split the bender setup into it's own playbook and removed some redundant stuff
- Renamed the job on Jenkins to better reflect the two jobs:

https://jenkins.fourkitchens.com/view/Training%20Wheels/job/build-stable-tw-ec2-instance/

https://jenkins.fourkitchens.com/view/Training%20Wheels/job/build-master-tw-ec2-instance/

Currently rebuilding due to me just committing to this branch - once you pull, I will update to 'stable' and 'master' and rebuild.

**Comment by elliotttf** [comment]
This is awesome, thanks for the cleanup!

**Pull request merged**
